### DISCUSSION TITLE
Welcome to esp-idf-ci-action Discussions!

### DISCUSSION THREAD

**Discussion by georgik** [espressif/esp-idf-ci-action#1] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by georgik** [comment]
I'd like to say thank you to all contributors to GitHub's actions and invite you to the discussion about improvements to this open-source repository under Espressif Systems umbrella.

This fork originates from the work of @sebastianPsm and @atanisoft . Big thank you for starting this repo.

I'd like to invite to the discussion also authors of other forks. Please join us here - @Igorprostoff, @bjpellegrino, @chriku, @josschne, @KitesForFuture.

Let me share with you the result of research and updates in this fork.

ESP-IDF official image is regularly published on Docker Hub https://hub.docker.com/r/espressif/idf . Images have the same tag name as github.com/espressif/esp-idf repo. The "latest" tag is being built from "master". The base image is Ubuntu 18.

**Update 1.**

One feature that was requested a lot is to have the posibility to switch between different versions of esp-idf on GitHub. This is a little bit tricky because GitHub does not allow you to use a variable in Dockerfile FROM field. One option to resolve this limitation is to create a branch of this Action for each major branch/tag in Docker Hub. This repository contains those tags. Then the user can specify GitHub action in the following way in `uses`:
```
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@latest
      with:
        path: 'esp32-s2-hmi-devkit-1/examples/smart-panel'
```

**Update 2.**

The second update that I'd like to share might be interesting for Rust users. We created a new image based on the original esp-idf with an additional Rust layer which supports build from Xtensa based on repository: https://github.com/espressif/rust-esp32-example
The image has the tag `rust-latest`:
```
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@rust-latest
```

You can find an example with artifacts here: https://github.com/espressif/rust-esp32-example/blob/feature/dockerfile/.github/workflows/test-build.yml

Please, feel free to join the discussion.
