### ISSUE TITLE
How to pass environment variables to the build? (RDT-308)

### ISSUE THREAD

**Issue by rodja** [espressif/esp-idf-ci-action#23]
I would like to set PROJECT_VER and PROJECT_NAME environment variables. How can this be accomplished?

**Comment by kumekay** [comment]
Hi @rodja 

You can override the default command in your workflow:

```
...
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        command: 'PROJECT_VER="1.0.0" idf.py build'
```
