### ISSUE TITLE
Using path corrupts git describe (RDT-344)

### ISSUE THREAD

**Issue by timoxd7** [espressif/esp-idf-ci-action#25]
## Problem
Using the path parameter will set the working directory for the docker container to this set path.

### Example file structure
- Project
  - .git
  - sub-folder
    - src
    - CMakeLists.txt
    - ...
  - ...

If now the sub-folder is used as "path" parameter, the .git folder will not be visible inside the docker container. This will lead to different behavior then running the "idf.py build" command directly, as in the normal herachie the "git describe --tags" command will also search in parent folders.

## Fix
Add a second parameter, to specify "working-dir" and "build-path" to do some kind of using the "working-dir" as volume for docker, but then run "cd build-path" inside the docker container. Don't know how to simply do this inside this extension, but might need to update the docker image as well.

**Comment by kumekay** [comment]
@timoxd7 Thank you for the issue, 
as a workaround, you can unset `path` parameter (mount whole repo) and add a custom command with CWD

```
jobs:
  build:
    ...
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        command: idf.py -C ./sub-folder build 
```
