### ISSUE TITLE
A lot of blank lines when running build (RDT-359)

### ISSUE THREAD

**Issue by enricobertolotti** [espressif/esp-idf-ci-action#28]
Is there a reason there are so many blank lines when running this action? All in all this action outputs around ~1k lines, most of them blank. It makes it hard to inspect the output

<img width="639" alt="image" src="https://user-images.githubusercontent.com/73933383/211400770-e6847430-18c5-4b82-a9d7-91100ed6ec63.png">

### Setup:
Self-hosted on ubuntu (rpi)

### Workflow:
```yaml
jobs:
  build:
    steps:
      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0
          target: esp32s2
          path: '.'
```
