### ISSUE TITLE
Unable to give custom path to build (RDT-536)

### ISSUE THREAD

**Issue by usmanmehmoodSSP** [espressif/esp-idf-ci-action#34]
I am checking out my code to a specific folder and when I give the same folder to the action's path, it appends some stuff to it.

This is my action.yaml
```yaml
- name: Checkout Application Code
  uses: actions/checkout@v3
  with:
    path: ${{ github.workspace }}/application

- name: esp-idf build
  uses: espressif/esp-idf-ci-action@v1
  with:
    esp_idf_version: v5.1
    target: esp32c3
    path: ${{ github.workspace }}/application

- name: Upload build
  uses: actions/upload-artifact@v3
  with:
    name: FirmwareFiles
    path: ${{ github.workspace }}/application/build/app_name.bin
```

And during the build process it's not able to find it and says this

```shell
CMakeLists.txt not found in project directory /app/my_username/app_name/home/runner/work/app_name/app_name/application
```

So as I see it, it is appending `/app/my_username/app_name` to `${{ github.workspace }}/application`
