### ISSUE TITLE
Difficulty Accessing Private GitHub Repo with IDF Component Manager in CI Pipeline (RDT-637)

### ISSUE THREAD

**Issue by hayschan** [espressif/esp-idf-ci-action#38]
Hello,

I'm encountering an issue with `espressif/esp-idf-ci-action@v1` while trying to build a project in my CI pipeline. The project uses the IDF Component Manager to fetch a component from a private GitHub repository.

Despite several attempts, I'm unable to grant access to the private repository for the IDF Component Manager running on GitHub. I've tried methods similar to those discussed in [this forum post](https://esp32.com/viewtopic.php?f=13&p=125861), including using ssh-agent and configuring known_hosts, but to no avail.

Could you please clarify:
1. Is `espressif/esp-idf-ci-action` designed to support accessing private repositories through the IDF Component Manager using `idf_component.yml`?
    ```yaml
    ## IDF Component Manager Manifest File
    dependencies:
      espressif/button: "^2.5.0"
      ## Required IDF version
      idf:
        version: ">=4.1.0"
    
      # For components in git repository:
      esp_arithmetic:
        path: "./component_add"
        version: "*"
        git: "git@github.com:kaspernyhus/multi_component_test.git"
    ```
2. If supported, could you provide guidance or examples on how to configure this correctly?
